/**
 * Builds a compact `server/navdata.ts` module from the WC3 binaries.
 * Stores the pathing grid as a base64-encoded bit-packed Uint8Array (~60KB)
 * instead of the verbose JSON boolean array (~1.5MB).
 *
 * Usage:  pnpm tsx scripts/build-navdata-compact.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { parseW3E } from '../src/world/wc3/W3EParser';
import { parseWpm, isCellWalkable, PATH_CELL_SIZE } from '../src/world/wc3/WpmParser';
import { parseDoo } from '../src/world/wc3/DooParser';
import { buildNavGridFromWpm, findWalkableNearOnGrid } from '../src/sim/buildWorld';
import { NavGrid } from '../src/navigation/NavGrid';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ASSETS_DIR = path.resolve(__dirname, '..', 'assets');
const SERVER_DIR = path.resolve(__dirname, '..', 'server');

function readFile(name: string): ArrayBuffer {
  const p = path.join(ASSETS_DIR, name);
  if (!fs.existsSync(p)) throw new Error(`missing asset: ${p}`);
  const buf = fs.readFileSync(p);
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
}

function wc3ToWorld(x: number, y: number): { wx: number; wz: number } {
  return { wx: x, wz: -y };
}

function main() {
  const w3eBuf = readFile('war3map.w3e');
  const wpmBuf = readFile('war3map.wpm');
  const dooBuf = readFile('war3map.doo');

  const terrain = parseW3E(w3eBuf);
  const pathing = parseWpm(wpmBuf);
  const doodads = parseDoo(dooBuf);

  const tilesW = terrain.width - 1;
  const tilesH = terrain.height - 1;
  if (pathing.width !== tilesW * 4 || pathing.height !== tilesH * 4) {
    throw new Error('pathing/terrain mismatch');
  }

  // ── Build the nav grid (WPM + tree footprints) and bit-pack it ──
  // Same code path as the client's buildSimWorld, so the grids are identical.
  const bounds = { minX: terrain.offsetX, minZ: -(terrain.offsetY + tilesH * 128) };
  const bare = buildNavGridFromWpm(pathing, bounds);
  const navGrid = buildNavGridFromWpm(pathing, bounds, doodads);
  logTreeStamping(bare, navGrid);

  // Bits stay in WPM-native order (row 0 = south); NavGrid row 0 = north.
  const numCells = pathing.width * pathing.height;
  const bytes = new Uint8Array(Math.ceil(numCells / 8));
  for (let i = 0; i < numCells; i++) {
    const row = Math.floor(i / pathing.width);
    const col = i % pathing.width;
    if (navGrid.isWalkable(col, pathing.height - 1 - row)) {
      bytes[Math.floor(i / 8)] |= 1 << (i % 8);
    }
  }
  const cellsBase64 = Buffer.from(bytes).toString('base64');

  // ── Height grid (full resolution float array → base64) ──
  const heightsBase64 = Buffer.from(new Uint8Array(terrain.finalHeight.buffer)).toString('base64');

  // ── Obstacles (projectile collision: solid rocks only — trees don't block arrows) ──
  const ROCK_STYLES = new Set(['ARrk', 'LRrk', 'LPcr']);
  const obsLines: string[] = [];
  for (const d of doodads) {
    if (!ROCK_STYLES.has(d.typeId)) continue;
    const { wx, wz } = wc3ToWorld(d.x, d.y);
    const col = Math.floor((d.x - terrain.offsetX) / PATH_CELL_SIZE);
    const row = Math.floor((d.y - terrain.offsetY) / PATH_CELL_SIZE);
    if (!isCellWalkable(pathing, col, row)) {
      const halfW = 40 * d.scaleX;
      const halfD = 40 * d.scaleY;
      obsLines.push(`  { minX: ${(wx - halfW).toFixed(1)}, minZ: ${(wz - halfD).toFixed(1)}, maxX: ${(wx + halfW).toFixed(1)}, maxZ: ${(wz + halfD).toFixed(1)} }`);
    }
  }

  // ── Arena (terrain 1) ──
  const arena = arenaFromWc3(-2784, -6720, 4416, 512);

  // ── Shop position (on the stamped grid, so it can't land inside a tree) ──
  const shopPos = findWalkableNearOnGrid(navGrid, arena.centerX, arena.centerZ);

  // ── Generate the module ──
  const ts = `/**
 * Compact navdata for the Durable Object server.
 * Auto-generated by scripts/build-navdata-compact.ts — do not edit.
 *
 * Pathing grid is bit-packed (1 = walkable).  Decode with:
 *   const byte = cellsBase64[i >> 3];
 *   const walkable = (byte >> (i & 7)) & 1;
 */
export const NAVDATA = {
  /** Bit-packed walkable cells, 1 bit per cell, row-major (south-to-north). */
  navGrid: {
    width: ${pathing.width},
    height: ${pathing.height},
    cellSize: ${PATH_CELL_SIZE},
    originX: ${terrain.offsetX},
    originZ: ${-(terrain.offsetY + tilesH * 128)},
    /** Base64-encoded Uint8Array of bit-packed walkable booleans. */
    cellsBase64: "${cellsBase64}",
  },

  /** Full-resolution height grid (Float32Array). */
  heightGrid: {
    width: ${terrain.width},
    height: ${terrain.height},
    /** Base64-encoded Float32Array of world-space elevations. */
    heightsBase64: "${heightsBase64}",
  },

  /** Solid doodad AABBs (projectile collision). */
  obstacles: [
${obsLines.join(',\n')}
  ],

  arenas: {
    terrain1: ${JSON.stringify(arena)},
  },

  shopPos: { x: ${shopPos.x.toFixed(1)}, z: ${shopPos.z.toFixed(1)} },
} as const;
`;

  const outPath = path.join(SERVER_DIR, 'navdata.ts');
  fs.mkdirSync(SERVER_DIR, { recursive: true });
  fs.writeFileSync(outPath, ts, 'utf-8');
  console.log(`[build-navdata-compact] wrote ${outPath}  ` +
    `(${pathing.width}x${pathing.height} pathing, ${obsLines.length} obstacles, ` +
    `${(Buffer.byteLength(ts) / 1024).toFixed(0)} KB)`);
}

// ── Helpers ───────────────────────────────────────────────────────────

function arenaFromWc3(minx: number, miny: number, maxx: number, maxy: number) {
  const minZ = -maxy;
  const maxZ = -miny;
  return {
    minX: minx, minZ, maxX: maxx, maxZ,
    centerX: (minx + maxx) / 2,
    centerZ: (minZ + maxZ) / 2,
    width: maxx - minx,
    height: maxZ - minZ,
  };
}

function countWalkable(grid: NavGrid): number {
  let n = 0;
  for (let gz = 0; gz < grid.height; gz++) {
    for (let gx = 0; gx < grid.width; gx++) {
      if (grid.isWalkable(gx, gz)) n++;
    }
  }
  return n;
}

function logTreeStamping(before: NavGrid, after: NavGrid): void {
  const total = before.width * before.height;
  const a = countWalkable(before);
  const b = countWalkable(after);
  console.log(
    `[build-navdata-compact] tree stamping blocked ${a - b} cells ` +
    `(walkable ${((a / total) * 100).toFixed(1)}% → ${((b / total) * 100).toFixed(1)}%)`,
  );
}

main();
