/**
 * Builds a compact `server/navdata.ts` module holding every playable map:
 *  - 'arena': parsed from the WC3 binaries in `assets/`
 *  - 'test':  generated in code (src/world/testMap.ts)
 *
 * Pathing grids are stored as base64-encoded bit-packed Uint8Arrays (~60KB
 * for the arena) instead of verbose JSON boolean arrays (~1.5MB).
 *
 * Usage:  pnpm tsx scripts/build-navdata-compact.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { parseW3E, W3ETerrain } from '../src/world/wc3/W3EParser';
import { parseWpm, isCellWalkable, PATH_CELL_SIZE, WpmPathing } from '../src/world/wc3/WpmParser';
import { parseDoo, DoodadPlacement } from '../src/world/wc3/DooParser';
import { buildNavGridFromWpm, findWalkableNearOnGrid } from '../src/sim/buildWorld';
import { NavGrid } from '../src/navigation/NavGrid';
import { buildTestMapData, testMapObstacles, TEST_MAP_ARENA } from '../src/world/testMap';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ASSETS_DIR = path.resolve(__dirname, '..', 'assets');
const SERVER_DIR = path.resolve(__dirname, '..', 'server');

interface ObstacleAABB {
  minX: number;
  minZ: number;
  maxX: number;
  maxZ: number;
}

interface ArenaRect {
  minX: number;
  minZ: number;
  maxX: number;
  maxZ: number;
  centerX: number;
  centerZ: number;
  width: number;
  height: number;
}

function readFile(name: string): ArrayBuffer {
  const p = path.join(ASSETS_DIR, name);
  if (!fs.existsSync(p)) throw new Error(`missing asset: ${p}`);
  const buf = fs.readFileSync(p);
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
}

function wc3ToWorld(x: number, y: number): { wx: number; wz: number } {
  return { wx: x, wz: -y };
}

function main() {
  const entries: string[] = [];

  // ── 'arena': the original WC3 map ──
  {
    const terrain = parseW3E(readFile('war3map.w3e'));
    const pathing = parseWpm(readFile('war3map.wpm'));
    const doodads = parseDoo(readFile('war3map.doo'));

    const tilesW = terrain.width - 1;
    const tilesH = terrain.height - 1;
    if (pathing.width !== tilesW * 4 || pathing.height !== tilesH * 4) {
      throw new Error('pathing/terrain mismatch');
    }

    // Obstacles: solid rocks only — trees don't block arrows.
    const ROCK_STYLES = new Set(['ARrk', 'LRrk', 'LPcr']);
    const obstacles: ObstacleAABB[] = [];
    for (const d of doodads) {
      if (!ROCK_STYLES.has(d.typeId)) continue;
      const { wx, wz } = wc3ToWorld(d.x, d.y);
      const col = Math.floor((d.x - terrain.offsetX) / PATH_CELL_SIZE);
      const row = Math.floor((d.y - terrain.offsetY) / PATH_CELL_SIZE);
      if (!isCellWalkable(pathing, col, row)) {
        const halfW = 40 * d.scaleX;
        const halfD = 40 * d.scaleY;
        obstacles.push({ minX: wx - halfW, minZ: wz - halfD, maxX: wx + halfW, maxZ: wz + halfD });
      }
    }

    const arena = arenaFromWc3(-2784, -6720, 4416, 512);
    entries.push(buildEntry('arena', terrain, pathing, doodads, arena, obstacles));
  }

  // ── 'test': the tiny generated debug map ──
  {
    const map = buildTestMapData();
    entries.push(buildEntry('test', map.terrain, map.pathing, map.doodads, { ...TEST_MAP_ARENA }, testMapObstacles()));
  }

  const ts = `/**
 * Compact navdata for the Durable Object server, one entry per map.
 * Auto-generated by scripts/build-navdata-compact.ts — do not edit.
 *
 * Pathing grids are bit-packed (1 = walkable).  Decode with:
 *   const byte = cellsBase64[i >> 3];
 *   const walkable = (byte >> (i & 7)) & 1;
 */
export const NAVDATA = {
${entries.join(',\n')}
} as const;

export type NavdataMapName = keyof typeof NAVDATA;
`;

  const outPath = path.join(SERVER_DIR, 'navdata.ts');
  fs.mkdirSync(SERVER_DIR, { recursive: true });
  fs.writeFileSync(outPath, ts, 'utf-8');
  console.log(`[build-navdata-compact] wrote ${outPath}  (${(Buffer.byteLength(ts) / 1024).toFixed(0)} KB)`);
}

/** Serialize one map's navdata entry (shared by every map source). */
function buildEntry(
  name: string,
  terrain: W3ETerrain,
  pathing: WpmPathing,
  doodads: DoodadPlacement[],
  arena: ArenaRect,
  obstacles: ObstacleAABB[],
): string {
  const tilesH = terrain.height - 1;
  const bounds = { minX: terrain.offsetX, minZ: -(terrain.offsetY + tilesH * 128) };

  // Same code path as the client's buildSimWorld, so the grids are identical.
  const bare = buildNavGridFromWpm(pathing, bounds);
  const navGrid = buildNavGridFromWpm(pathing, bounds, doodads);
  logTreeStamping(name, bare, navGrid);

  // Bits stay in WPM-native order (row 0 = south); NavGrid row 0 = north.
  const numCells = pathing.width * pathing.height;
  const bytes = new Uint8Array(Math.ceil(numCells / 8));
  for (let i = 0; i < numCells; i++) {
    const row = Math.floor(i / pathing.width);
    const col = i % pathing.width;
    if (navGrid.isWalkable(col, pathing.height - 1 - row)) {
      bytes[Math.floor(i / 8)] |= 1 << (i % 8);
    }
  }
  const cellsBase64 = Buffer.from(bytes).toString('base64');

  // Full-resolution height grid (Float32Array → base64).
  const heightsBase64 = Buffer.from(new Uint8Array(terrain.finalHeight.buffer)).toString('base64');

  // Shop position (on the stamped grid, so it can't land inside a tree).
  const shopPos = findWalkableNearOnGrid(navGrid, arena.centerX, arena.centerZ);

  const obsLines = obstacles.map((o) =>
    `      { minX: ${o.minX.toFixed(1)}, minZ: ${o.minZ.toFixed(1)}, maxX: ${o.maxX.toFixed(1)}, maxZ: ${o.maxZ.toFixed(1)} }`,
  );

  return `  ${name}: {
    /** Bit-packed walkable cells, 1 bit per cell, row-major (south-to-north). */
    navGrid: {
      width: ${pathing.width},
      height: ${pathing.height},
      cellSize: ${PATH_CELL_SIZE},
      originX: ${terrain.offsetX},
      originZ: ${-(terrain.offsetY + tilesH * 128)},
      /** Base64-encoded Uint8Array of bit-packed walkable booleans. */
      cellsBase64: "${cellsBase64}",
    },

    /** Full-resolution height grid (Float32Array). */
    heightGrid: {
      width: ${terrain.width},
      height: ${terrain.height},
      /** Base64-encoded Float32Array of world-space elevations. */
      heightsBase64: "${heightsBase64}",
    },

    /** Solid doodad AABBs (projectile collision). */
    obstacles: [
${obsLines.join(',\n')}
    ],

    arena: ${JSON.stringify(arena)},

    shopPos: { x: ${shopPos.x.toFixed(1)}, z: ${shopPos.z.toFixed(1)} },
  }`;
}

// ── Helpers ───────────────────────────────────────────────────────────

function arenaFromWc3(minx: number, miny: number, maxx: number, maxy: number): ArenaRect {
  const minZ = -maxy;
  const maxZ = -miny;
  return {
    minX: minx, minZ, maxX: maxx, maxZ,
    centerX: (minx + maxx) / 2,
    centerZ: (minZ + maxZ) / 2,
    width: maxx - minx,
    height: maxZ - minZ,
  };
}

function countWalkable(grid: NavGrid): number {
  let n = 0;
  for (let gz = 0; gz < grid.height; gz++) {
    for (let gx = 0; gx < grid.width; gx++) {
      if (grid.isWalkable(gx, gz)) n++;
    }
  }
  return n;
}

function logTreeStamping(name: string, before: NavGrid, after: NavGrid): void {
  const total = before.width * before.height;
  const a = countWalkable(before);
  const b = countWalkable(after);
  console.log(
    `[build-navdata-compact] ${name}: tree stamping blocked ${a - b} cells ` +
    `(walkable ${((a / total) * 100).toFixed(1)}% → ${((b / total) * 100).toFixed(1)}%)`,
  );
}

main();
